import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { AuditSession } from '@/lib/store/db';

export const exportAuditReport = (session: AuditSession) => {
    const doc = new jsPDF();
    const NAVY = [15, 23, 42]; // #0F172A
    const RED = [190, 18, 60]; // #be123c

    // ---------------------------------------------------------
    // PAGE 1: EXECUTIVE SUMMARY
    // ---------------------------------------------------------

    doc.setFont('times', 'bold');
    doc.setFontSize(24);
    doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);
    doc.text('LEXMETRIC AUDIT REPORT', 14, 22);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('Forensic Medicaid Lookback Audit', 14, 28);

    // Divider
    doc.setDrawColor(200);
    doc.line(14, 32, 196, 32);

    // Client Info Box
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text(`Client: ${session.clientName || 'Untitled Client'}`, 14, 45);
    doc.text(`Audit ID: ${session._id.slice(0, 8)}`, 14, 52);
    doc.text(`Date Generated: ${new Date().toLocaleDateString()}`, 14, 59);

    // Calc Metrics (Filter out SAFE/IGNORED)
    const activeFlags = session.flags.filter(f => f.status !== 'SAFE' && f.status !== 'IGNORED');
    const totalExposure = activeFlags.reduce((sum, flag) => {
        const tx = session.transactions.find(t => t.id === flag.transactionId);
        return sum + (tx ? Math.abs(tx.amount) : 0);
    }, 0);

    // Penalty Calculation (Mock Logic for MVP)
    const DIVISOR = 10438; // Default FL
    const penaltyMonths = (totalExposure / DIVISOR).toFixed(2);

    // Metrics Box
    doc.setFillColor(248, 250, 252); // Slate-50
    doc.rect(14, 70, 182, 50, 'F');
    doc.setDrawColor(226, 232, 240);
    doc.rect(14, 70, 182, 50, 'S');

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('TOTAL PENALTY EXPOSURE', 20, 80);

    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(RED[0], RED[1], RED[2]);
    doc.text(`$${totalExposure.toLocaleString(undefined, { minimumFractionDigits: 2 })}`, 20, 92);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text('ESTIMATED INELIGIBILITY PERIOD', 110, 80);

    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);
    doc.text(`${penaltyMonths} Months`, 110, 92);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(150);
    doc.text(`Based on regional divisor of $${DIVISOR.toLocaleString()}/mo`, 110, 100);

    // Disclaimer
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(100);
    const disclaimer = "This report is generated by LexMetric for attorney use only. It identifies transactions that match typical Medicaid penalty patterns (uncompensated transfers, irregular withdrawals). Final determination of penalty status is a legal matter.";
    doc.text(doc.splitTextToSize(disclaimer, 180), 14, 135);

    // ---------------------------------------------------------
    // PAGE 2+: HOT LIST TABLE
    // ---------------------------------------------------------
    doc.addPage();

    // Secondary Header
    doc.setFontSize(14);
    doc.setTextColor(NAVY[0], NAVY[1], NAVY[2]);
    doc.setFont('times', 'bold');
    doc.text('Schedule A: Flagged Transactions', 14, 20);

    const flaggedData = activeFlags.map(flag => {
        const tx = session.transactions.find(t => t.id === flag.transactionId);
        return [
            tx?.date || 'N/A',
            tx?.description || 'Unknown',
            tx ? `$${Math.abs(tx.amount).toFixed(2)}` : '$0.00',
            flag.ruleId.replace(/_/g, ' '),
            flag.status
        ];
    }).sort((a, b) => new Date(a[0]).getTime() - new Date(b[0]).getTime());

    autoTable(doc, {
        startY: 30,
        head: [['Date', 'Description', 'Amount', 'Risk Category', 'Status']],
        body: flaggedData,
        theme: 'plain',
        styles: {
            fontSize: 9,
            cellPadding: 4,
            lineColor: [226, 232, 240], // slate-200
            lineWidth: 0.1,
            textColor: [51, 65, 85] // slate-700
        },
        headStyles: {
            fillColor: [241, 245, 249], // slate-100
            textColor: NAVY as [number, number, number], // Navy
            fontStyle: 'bold',
            lineColor: [203, 213, 225], // slate-300
            lineWidth: 0.1,
        },
        alternateRowStyles: {
            fillColor: [255, 255, 255]
        },
        columnStyles: {
            0: { cellWidth: 25 },
            1: { cellWidth: 'auto' },
            2: { cellWidth: 30, halign: 'right', fontStyle: 'bold', textColor: RED as [number, number, number] }, // Red amount
            3: { cellWidth: 40 },
            4: { cellWidth: 25 }
        },
        didDrawPage: () => {
            // Footer on every page
            const pageCount = doc.internal.getNumberOfPages();
            const width = doc.internal.pageSize.getWidth();
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.setFont('helvetica', 'italic');
            doc.text(`LexMetric Confidential - Page ${pageCount}`, width / 2, 287, { align: 'center' });
        }
    });

    // Save
    const safeClientName = (session.clientName || 'Untitled').replace(/[^a-z0-9]/gi, '_');
    const filename = `LexMetric_Audit_${safeClientName}_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(filename);
};
